// This file is generated by Slice Machine. Update with care!

import IconsArea from './IconsArea';
import ProjectGallery from './ProjectGallery';
import Projects from './Projects';
import Services from './Services';
import Team from './Team';

export {
	IconsArea,
	ProjectGallery,
	Projects,
	Services,
	Team,
};

export const components = {
	icons_area: IconsArea,
	project_gallery: ProjectGallery,
	projects: Projects,
	services: Services,
	team: Team,
};
